---
Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false
